version: '2'

services:
   webapp:
     build: .
     ports:
       - "3000:3000"
     depends_on:
       - db
     environment:
       - DATABASE_HOST=db
   db:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: sketch-my-word
volumes:
    db_data: